### ISSUE TITLE
If I edit my herds and add a new one, when I go back to my herds is not shown.

### ISSUE THREAD

**Issue by airenzp** [NBISweden/theherdbook#403]
I needed to restart the website to reload my herds

**Comment by HenrikeW** [comment]
For clarification: 
Are you adding a new herd? Or a new individual or a new breeding, for example? 
In one of the last two cases this could be a duplicate of #404.
If you are adding a new herd: Are you doing that as an owner or as admin? I suppose as admin, because if you are only an owner, you shouldn't be able to add yourself a new herd, right?
