### ISSUE TITLE
In parningstillfällen list bug and select parent bug

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#426]
The table show breeding events of the animals the herd is currently owning.
The table should list breeding that happened for any animal when they belong to this herd. So it should include breedings for a animal even if its sold to another herd if they where breed during the stay in the current herd.

**Comment by HenrikeW** [comment]
The endpoint that is used to get the breedings for the current herd looks like this:
```
@APP.route("/api/breeding/<h_id>")
@login_required
def breeding_list(h_id):
    """
    Returns a list of all breeding events connected to a given herd.
    A breeding event is considered linked to a herd if any of the parents are
    currently in the herd.
    """
    breedings = da.get_breeding_events(h_id, session.get("user_id", None))
    return jsonify(breedings=breedings)
```
So it explicitly has another definition of which breedings should be shown. The function it calls in `data_access.py` works according to it. 
Are we sure we want to change this definition now? 
If yes, at least this part of the bug is rather a backend than a frontend issue I believe.

**Comment by jhagberg** [comment]
Yes we need to update and refine the breeding list sql question
